name: NBA → Google Sheets (Players Stats)

on:
  workflow_dispatch:   # Lancement manuel
  schedule:
    # Tous les jours à 03:00 UTC (meilleur créneau pour l'API NBA)
    - cron: "0 3 * * *"

jobs:
  nba-to-sheets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install nba_api pandas google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Créer le fichier credentials Google
        run: |
          printf "%s" "$GOOGLE_CREDENTIALS" > google-credentials.json

      - name: Lancer le script NBA
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          python main_players.py
